services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    # volumes:
    #   - ./frontend:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING : "true"
    ports:
      - "5173:8080"
    
    
  backend:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING : "true"
    ports:
      - "5500:6969"
  
  peerjs:
      container_name: peerjs
      image: peerjs/peerjs-server
      command: peerjs --port 9000 --key peerjs --path /myapp
      ports:
        - "9000:9000"
    
    
