services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5173:8080"
    
    
  backend:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
    ports:
      - "5500:6969"
    
    
